# Generated by Django 4.0.1 on 2022-01-31 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_note_options_note_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={},
        ),
    ]
