# Generated by Django 4.0.1 on 2022-01-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_note_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="body",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
